# oh my zsh conf
plugins=(git colored-man-pages z cp extract history copydir sudo command-not-found jump)
export ZSH=$HOME/.oh-my-zsh
export TERM=xterm-256color
ZSH_THEME="robbyrussell"
HIST_STAMPS="yyyy-mm-dd"
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt nonomatch
source $ZSH/oh-my-zsh.sh

# proxy conf
#export http_proxy="http://127.0.0.1:12333"
#export https_proxy="http://127.0.0.1:12333"

# autosuggest conf
source ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=247,bold,underline"

# alias conf
alias CL='clang-format-3.8 -i'
alias ll='ls -alh'
alias l='ls -lh'
alias g='git status'
alias gb='git branch -avv'
alias t='tig'
alias c='clang-format-3.8 -i'
alias vi='vim'
alias v='vim'
alias cp='cpv'
alias rm='trash-put'


# fzf conf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey '^f' vi-forward-word
bindkey '^b' vi-backward-word
export FZF_DEFAULT_COMMAND='ag -g '

# navi conf
#export NAVI_PATH=~/.config/haoming/Cheats
#eval "$(navi widget zsh)"

# distcc
#export CCACHE_PREFIX="distcc"
#export CC="ccache gcc" CXX="ccache g++"
#export DISTCC_HOSTS="192.168.3.92/16 localhost/8"
#export DISTCC_LOG="/var/log/trunk/distcc"

source /opt/ros/kinetic/setup.zsh
source /opt/trunk_master/setup.zsh

